In [ ]:
import nltk
import os
import nltk.corpus

In [ ]:
#doc_path=input("Give the path of document:")
import string
def Document(*doc_path):
  doc_list=[]
  for p in doc_path:
    df=''
    df=open(p,"r")
    i=df.read()
    #for punctuation removal
    punct = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    for ele in i:
      if ele in punct:
        i= i.replace(ele, "")
    #tokenization
    doc_list.append(i.split())
    
  return doc_list

In [ ]:
def tokenise(doc_list):
  tokens=[]
  for y in doc_list:
    tokens.append(y.split())
  return tokens

In [ ]:
def stopwords(tokens):
  from nltk.corpus import stopwords
  nltk.download('stopwords')
  stop_words = stopwords.words('english')
  txt=[]
  output=[]
  for li in tokens:
    for i in range(0,len(li)):
      word=li[i]
      word=word.lower()
      if word not in stop_words:
            output.append(li[i])
            #txt = (" ").join(output)
  return output

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stop_words = stopwords.words('english')
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
import string
def punctuation(tokens):
  pnkt=[]
  for t in tokens:
    if t not in string.punctuation:
      pnkt.append(t)
  return pnkt

In [ ]:
def unique_words(pnkt):
  tx=[]
  for t in pnkt:
    if t not in tx:
      tx.append(t)

  return(tx)

In [ ]:
def indexing(w_list,index,q):
#q should be the output list of Document() function
#w_list should be the output list of unique_words() function
  for wd in w_list:
    for w in range(0,len(q)):
      if wd in q[w]:
        index[w].append(1)
      else:
        index[w].append(0)
  return index

In [ ]:
o=Document(r"/content/india.txt",r"/content/un.txt",r"/content/undp.txt")

In [ ]:
print(o)

[['India', 'country', 'that', 'occupies', 'the', 'greater', 'part', 'of', 'South', 'Asia', 'Its', 'capital', 'is', 'New', 'Delhi', 'built', 'in', 'the', '20th', 'century', 'just', 'south', 'of', 'the', 'historic', 'hub', 'of', 'Old', 'Delhi', 'to', 'serve', 'as', 'India’s', 'administrative', 'centre', 'Its', 'government', 'is', 'a', 'constitutional', 'republic', 'that', 'represents', 'a', 'highly', 'diverse', 'population', 'consisting', 'of', 'thousands', 'of', 'ethnic', 'groups', 'and', 'likely', 'hundreds', 'of', 'languages', 'With', 'roughly', 'onesixth', 'of', 'the', 'world’s', 'total', 'population', 'India', 'is', 'the', 'second', 'most', 'populous', 'country', 'after', 'China', 'It', 'is', 'known', 'from', 'archaeological', 'evidence', 'that', 'a', 'highly', 'sophisticated', 'urbanized', 'culture—the', 'Indus', 'civilization—dominated', 'the', 'northwestern', 'part', 'of', 'the', 'subcontinent', 'from', 'about', '2600', 'to', '2000', 'BCE', 'From', 'that', 'period', 'on', 'India', 'functioned', 'as', 'a', 'virtually', 'selfcontained', 'political', 'and', 'cultural', 'arena', 'which', 'gave', 'rise', 'to', 'a', 'distinctive', 'tradition', 'that', 'was', 'associated', 'primarily', 'with', 'Hinduism', 'the', 'roots', 'of', 'which', 'can', 'largely', 'be', 'traced', 'to', 'the', 'Indus', 'civilization', 'Other', 'religions', 'notably', 'Buddhism', 'and', 'Jainism', 'originated', 'in', 'India—though', 'their', 'presence', 'there', 'is', 'now', 'quite', 'small—and', 'throughout', 'the', 'centuries', 'residents', 'of', 'the', 'subcontinent', 'developed', 'a', 'rich', 'intellectual', 'life', 'in', 'such', 'fields', 'as', 'mathematics', 'astronomy', 'architecture', 'literature', 'music', 'and', 'the', 'fine', 'arts'], ['The', 'United', 'Nations', 'is', 'an', 'international', 'organization', 'founded', 'in', '1945', 'Currently', 'made', 'up', 'of', '193', 'Member', 'States', 'the', 'UN', 'and', 'its', 'work', 'are', 'guided', 'by', 'the', 'purposes', 'and', 'principles', 'contained', 'in', 'its', 'founding', 'Charter', 'The', 'UN', 'has', 'evolved', 'over', 'the', 'years', 'to', 'keep', 'pace', 'with', 'a', 'rapidly', 'changing', 'world', 'But', 'one', 'thing', 'has', 'stayed', 'the', 'same', 'it', 'remains', 'the', 'one', 'place', 'on', 'Earth', 'where', 'all', 'the', 'world’s', 'nations', 'can', 'gather', 'together', 'discuss', 'common', 'problems', 'and', 'find', 'shared', 'solutions', 'that', 'benefit', 'all', 'of', 'humanity', 'The', 'UN’s', 'Membership', 'has', 'grown', 'from', 'the', 'original', '51', 'Member', 'States', 'in', '1945', 'to', 'the', 'current', '193', 'Member', 'States', 'All', 'UN', 'Member', 'States', 'are', 'members', 'of', 'the', 'General', 'Assembly', 'States', 'are', 'admitted', 'to', 'membership', 'by', 'a', 'decision', 'of', 'the', 'General', 'Assembly', 'upon', 'the', 'recommendation', 'of', 'the', 'Security', 'Council', 'The', 'main', 'bodies', 'of', 'the', 'UN', 'are', 'the', 'General', 'Assembly', 'the', 'Security', 'Council', 'the', 'Economic', 'and', 'Social', 'Council', 'the', 'Trusteeship', 'Council', 'the', 'International', 'Court', 'of', 'Justice', 'and', 'the', 'UN', 'Secretariat', 'All', 'were', 'established', 'in', '1945', 'when', 'the', 'UN', 'was', 'founded'], ['The', 'United', 'Nations', 'Development', 'Programme', 'UNDP', 'the', 'worldwide', 'development', 'network', 'of', 'the', 'United', 'Nations', 'is', 'the', 'world’s', 'most', 'significant', 'multilateral', 'source', 'of', 'development', 'aid', 'The', 'Expanded', 'Programme', 'of', 'Technical', 'Assistance', 'and', 'the', 'United', 'Nations', 'Special', 'Fund', 'were', 'merged', 'in', '1965', 'The', 'two', 'institutions', 'were', 'fully', 'integrated', 'into', 'the', 'UNDP', 'in', '1971', 'The', 'United', 'Nations', 'Development', 'Programme', 'UNDP', 'is', 'an', 'executive', 'body', 'of', 'the', 'United', 'Nations', 'General', 'Assembly', 'After', 'the', 'Secretary', 'and', 'the', 'Deputy', 'SecretaryGeneral', 'the', 'UNDP', 'Administrator', 'is', 'the', 'third', 'highestranking', 'member', 'of', 'the', 'UN', 'The', 'UNDP', 'is', 'based', 'in', 'New', 'York', 'City', 'and', 'is', 'fully', 'supported', 'by', 'voluntary', 'contributions', 'from', 'member', 'countries', 'In', '166', 'countries', 'the', 'organisation', 'operates', 'national', 'offices', 'where', 'it', 'works', 'with', 'local', 'governments', 'to', 'address', 'development', 'concerns', 'and', 'build', 'local', 'expertise', 'UNDP', 'offers', 'developing', 'nations', 'professional', 'advice', 'training', 'and', 'financial', 'funding', 'focusing', 'on', 'the', 'least', 'developed', 'countries', 'UNDP', 'works', 'on', 'poverty', 'reduction', 'HIVAIDS', 'democratic', 'governance', 'energy', 'and', 'environment', 'and', 'crisis', 'prevention', 'and', 'recovery', 'to', 'achieve', 'the', 'MDGs', 'and', 'support', 'global', 'development', 'In', 'all', 'of', 'its', 'activities', 'the', 'UNDP', 'promotes', 'the', 'preservation', 'of', 'human', 'rights', 'and', 'women’s', 'empowerment', 'UNDP', 'also', 'produces', 'an', 'annual', 'Human', 'Development', 'Report', 'to', 'track', 'and', 'assess', 'development', 'progress', 'In', 'addition', 'UNDP', 'releases', 'regional', 'national', 'and', 'local', 'Human', 'Development', 'Reports', 'in', 'addition', 'to', 'a', 'global', 'report']]

In [ ]:
def Dictionary(w_list,vec_list):
  wlst=[]
  ulst=[]
  for wd in w_list:
    li=[]
    wlst.append(wd)
    for w in range(0,len(vec_list)):
      if wd in vec_list[w]:
        li.append(1)
      else:
        li.append(0)
        ulst.append(li)

  wd_vec_dct=dict(zip(wlst,ulst)) 
  
  return(wd_vec_dct)

In [ ]:
q=stopwords(o)
print(q)

['India', 'country', 'occupies', 'greater', 'part', 'South', 'Asia', 'capital', 'New', 'Delhi', 'built', '20th', 'century', 'south', 'historic', 'hub', 'Old', 'Delhi', 'serve', 'India’s', 'administrative', 'centre', 'government', 'constitutional', 'republic', 'represents', 'highly', 'diverse', 'population', 'consisting', 'thousands', 'ethnic', 'groups', 'likely', 'hundreds', 'languages', 'roughly', 'onesixth', 'world’s', 'total', 'population', 'India', 'second', 'populous', 'country', 'China', 'known', 'archaeological', 'evidence', 'highly', 'sophisticated', 'urbanized', 'culture—the', 'Indus', 'civilization—dominated', 'northwestern', 'part', 'subcontinent', '2600', '2000', 'BCE', 'period', 'India', 'functioned', 'virtually', 'selfcontained', 'political', 'cultural', 'arena', 'gave', 'rise', 'distinctive', 'tradition', 'associated', 'primarily', 'Hinduism', 'roots', 'largely', 'traced', 'Indus', 'civilization', 'religions', 'notably', 'Buddhism', 'Jainism', 'originated', 'India—though', 'presence', 'quite', 'small—and', 'throughout', 'centuries', 'residents', 'subcontinent', 'developed', 'rich', 'intellectual', 'life', 'fields', 'mathematics', 'astronomy', 'architecture', 'literature', 'music', 'fine', 'arts', 'United', 'Nations', 'international', 'organization', 'founded', '1945', 'Currently', 'made', '193', 'Member', 'States', 'UN', 'work', 'guided', 'purposes', 'principles', 'contained', 'founding', 'Charter', 'UN', 'evolved', 'years', 'keep', 'pace', 'rapidly', 'changing', 'world', 'one', 'thing', 'stayed', 'remains', 'one', 'place', 'Earth', 'world’s', 'nations', 'gather', 'together', 'discuss', 'common', 'problems', 'find', 'shared', 'solutions', 'benefit', 'humanity', 'UN’s', 'Membership', 'grown', 'original', '51', 'Member', 'States', '1945', 'current', '193', 'Member', 'States', 'UN', 'Member', 'States', 'members', 'General', 'Assembly', 'States', 'admitted', 'membership', 'decision', 'General', 'Assembly', 'upon', 'recommendation', 'Security', 'Council', 'main', 'bodies', 'UN', 'General', 'Assembly', 'Security', 'Council', 'Economic', 'Social', 'Council', 'Trusteeship', 'Council', 'International', 'Court', 'Justice', 'UN', 'Secretariat', 'established', '1945', 'UN', 'founded', 'United', 'Nations', 'Development', 'Programme', 'UNDP', 'worldwide', 'development', 'network', 'United', 'Nations', 'world’s', 'significant', 'multilateral', 'source', 'development', 'aid', 'Expanded', 'Programme', 'Technical', 'Assistance', 'United', 'Nations', 'Special', 'Fund', 'merged', '1965', 'two', 'institutions', 'fully', 'integrated', 'UNDP', '1971', 'United', 'Nations', 'Development', 'Programme', 'UNDP', 'executive', 'body', 'United', 'Nations', 'General', 'Assembly', 'Secretary', 'Deputy', 'SecretaryGeneral', 'UNDP', 'Administrator', 'third', 'highestranking', 'member', 'UN', 'UNDP', 'based', 'New', 'York', 'City', 'fully', 'supported', 'voluntary', 'contributions', 'member', 'countries', '166', 'countries', 'organisation', 'operates', 'national', 'offices', 'works', 'local', 'governments', 'address', 'development', 'concerns', 'build', 'local', 'expertise', 'UNDP', 'offers', 'developing', 'nations', 'professional', 'advice', 'training', 'financial', 'funding', 'focusing', 'least', 'developed', 'countries', 'UNDP', 'works', 'poverty', 'reduction', 'HIVAIDS', 'democratic', 'governance', 'energy', 'environment', 'crisis', 'prevention', 'recovery', 'achieve', 'MDGs', 'support', 'global', 'development', 'activities', 'UNDP', 'promotes', 'preservation', 'human', 'rights', 'women’s', 'empowerment', 'UNDP', 'also', 'produces', 'annual', 'Human', 'Development', 'Report', 'track', 'assess', 'development', 'progress', 'addition', 'UNDP', 'releases', 'regional', 'national', 'local', 'Human', 'Development', 'Reports', 'addition', 'global', 'report']

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
u=unique_words(q)

In [ ]:
print(u)

['India', 'country', 'occupies', 'greater', 'part', 'South', 'Asia', 'capital', 'New', 'Delhi', 'built', '20th', 'century', 'south', 'historic', 'hub', 'Old', 'serve', 'India’s', 'administrative', 'centre', 'government', 'constitutional', 'republic', 'represents', 'highly', 'diverse', 'population', 'consisting', 'thousands', 'ethnic', 'groups', 'likely', 'hundreds', 'languages', 'roughly', 'onesixth', 'world’s', 'total', 'second', 'populous', 'China', 'known', 'archaeological', 'evidence', 'sophisticated', 'urbanized', 'culture—the', 'Indus', 'civilization—dominated', 'northwestern', 'subcontinent', '2600', '2000', 'BCE', 'period', 'functioned', 'virtually', 'selfcontained', 'political', 'cultural', 'arena', 'gave', 'rise', 'distinctive', 'tradition', 'associated', 'primarily', 'Hinduism', 'roots', 'largely', 'traced', 'civilization', 'religions', 'notably', 'Buddhism', 'Jainism', 'originated', 'India—though', 'presence', 'quite', 'small—and', 'throughout', 'centuries', 'residents', 'developed', 'rich', 'intellectual', 'life', 'fields', 'mathematics', 'astronomy', 'architecture', 'literature', 'music', 'fine', 'arts', 'United', 'Nations', 'international', 'organization', 'founded', '1945', 'Currently', 'made', '193', 'Member', 'States', 'UN', 'work', 'guided', 'purposes', 'principles', 'contained', 'founding', 'Charter', 'evolved', 'years', 'keep', 'pace', 'rapidly', 'changing', 'world', 'one', 'thing', 'stayed', 'remains', 'place', 'Earth', 'nations', 'gather', 'together', 'discuss', 'common', 'problems', 'find', 'shared', 'solutions', 'benefit', 'humanity', 'UN’s', 'Membership', 'grown', 'original', '51', 'current', 'members', 'General', 'Assembly', 'admitted', 'membership', 'decision', 'upon', 'recommendation', 'Security', 'Council', 'main', 'bodies', 'Economic', 'Social', 'Trusteeship', 'International', 'Court', 'Justice', 'Secretariat', 'established', 'Development', 'Programme', 'UNDP', 'worldwide', 'development', 'network', 'significant', 'multilateral', 'source', 'aid', 'Expanded', 'Technical', 'Assistance', 'Special', 'Fund', 'merged', '1965', 'two', 'institutions', 'fully', 'integrated', '1971', 'executive', 'body', 'Secretary', 'Deputy', 'SecretaryGeneral', 'Administrator', 'third', 'highestranking', 'member', 'based', 'York', 'City', 'supported', 'voluntary', 'contributions', 'countries', '166', 'organisation', 'operates', 'national', 'offices', 'works', 'local', 'governments', 'address', 'concerns', 'build', 'expertise', 'offers', 'developing', 'professional', 'advice', 'training', 'financial', 'funding', 'focusing', 'least', 'poverty', 'reduction', 'HIVAIDS', 'democratic', 'governance', 'energy', 'environment', 'crisis', 'prevention', 'recovery', 'achieve', 'MDGs', 'support', 'global', 'activities', 'promotes', 'preservation', 'human', 'rights', 'women’s', 'empowerment', 'also', 'produces', 'annual', 'Human', 'Report', 'track', 'assess', 'progress', 'addition', 'releases', 'regional', 'Reports', 'report']

In [ ]:
index=[]
tx1=[]
for d in range(1,len(o)+1):
  tx1.append(d)
  r=[]
  index.append(r)

print(index)
print(tx1)

[[], [], []]
[1, 2, 3]

In [ ]:
er=indexing(u,index,o)

In [ ]:
import pandas as pd
def data_frame(words,index,tx1):
  df = pd.DataFrame(words, columns=['words'])
  for g in range(0,len(tx1)):
    df['DOC{d}'.format(d=tx1[g])]=index[g]
  return df

In [ ]:
df=data_frame(u,er,tx1)

In [ ]:
df

        words  DOC1  DOC2  DOC3
0       India     1     0     0
1     country     1     0     0
2    occupies     1     0     0
3     greater     1     0     0
4        part     1     0     0
..        ...   ...   ...   ...
254  addition     0     0     1
255  releases     0     0     1
256  regional     0     0     1
257   Reports     0     0     1
258    report     0     0     1

[259 rows x 4 columns]

In [ ]:
df2=df

In [ ]:
df2

        words  DOC1  DOC2  DOC3
0       India     1     0     0
1     country     1     0     0
2    occupies     1     0     0
3     greater     1     0     0
4        part     1     0     0
..        ...   ...   ...   ...
254  addition     0     0     1
255  releases     0     0     1
256  regional     0     0     1
257   Reports     0     0     1
258    report     0     0     1

[259 rows x 4 columns]

In [ ]:
e=(df2.query("words=='India' or words=='part'"))
print(e)
type(e)

   words  DOC1  DOC2  DOC3
0  India     1     0     0
4   part     1     0     0

pandas.core.frame.DataFrame

In [ ]:
df2

        words  DOC1  DOC2  DOC3
0       India     1     0     0
1     country     1     0     0
2    occupies     1     0     0
3     greater     1     0     0
4        part     1     0     0
..        ...   ...   ...   ...
254  addition     0     0     1
255  releases     0     0     1
256  regional     0     0     1
257   Reports     0     0     1
258    report     0     0     1

[259 rows x 4 columns]

In [ ]:
der=Dictionary(u,o)
der

{'India': [1, 0, 0],
 'country': [1, 0, 0],
 'occupies': [1, 0, 0],
 'greater': [1, 0, 0],
 'part': [1, 0, 0],
 'South': [1, 0, 0],
 'Asia': [1, 0, 0],
 'capital': [1, 0, 0],
 'New': [1, 0, 0],
 'Delhi': [1, 0, 0],
 'built': [1, 0, 0],
 '20th': [1, 0, 0],
 'century': [1, 0, 0],
 'south': [1, 0, 0],
 'historic': [1, 0, 0],
 'hub': [1, 0, 0],
 'Old': [1, 0, 1],
 'serve': [1, 0, 0],
 'India’s': [1, 0, 0],
 'administrative': [1, 0, 0],
 'centre': [1, 0, 0],
 'government': [1, 0, 0],
 'constitutional': [1, 0, 0],
 'republic': [1, 0, 0],
 'represents': [1, 0, 0],
 'highly': [1, 0, 0],
 'diverse': [1, 0, 0],
 'population': [1, 0, 0],
 'consisting': [1, 0, 0],
 'thousands': [1, 0, 0],
 'ethnic': [1, 0, 0],
 'groups': [1, 0, 0],
 'likely': [1, 0, 0],
 'hundreds': [1, 0, 0],
 'languages': [1, 0, 0],
 'roughly': [1, 0, 0],
 'onesixth': [1, 0, 0],
 'world’s': [1, 0, 0],
 'total': [1, 0, 0],
 'second': [1, 0, 0],
 'populous': [1, 0, 0],
 'China': [1, 0, 0],
 'known': [1, 0, 0],
 'archaeological': [1, 0, 0],
 'evidence': [1, 0, 0],
 'sophisticated': [1, 0, 0],
 'urbanized': [1, 0, 0],
 'culture—the': [1, 0, 0],
 'Indus': [1, 0, 0],
 'civilization—dominated': [1, 0, 0],
 'northwestern': [1, 0, 0],
 'subcontinent': [1, 0, 0],
 '2600': [1, 0, 0],
 '2000': [1, 0, 0],
 'BCE': [1, 0, 0],
 'period': [1, 0, 0],
 'functioned': [1, 0, 0],
 'virtually': [1, 0, 0],
 'selfcontained': [1, 0, 0],
 'political': [1, 0, 0],
 'cultural': [1, 0, 0],
 'arena': [1, 0, 0],
 'gave': [1, 0, 0],
 'rise': [1, 0, 0],
 'distinctive': [1, 0, 0],
 'tradition': [1, 0, 0],
 'associated': [1, 0, 0],
 'primarily': [1, 0, 0],
 'Hinduism': [1, 0, 0],
 'roots': [1, 0, 0],
 'largely': [1, 0, 0],
 'traced': [1, 0, 0],
 'civilization': [1, 0, 0],
 'religions': [1, 0, 0],
 'notably': [1, 0, 0],
 'Buddhism': [1, 0, 0],
 'Jainism': [1, 0, 0],
 'originated': [1, 0, 0],
 'India—though': [1, 0, 0],
 'presence': [1, 0, 0],
 'quite': [1, 0, 0],
 'small—and': [1, 0, 0],
 'throughout': [1, 0, 0],
 'centuries': [1, 0, 0],
 'residents': [1, 0, 0],
 'developed': [1, 0, 0],
 'rich': [1, 0, 0],
 'intellectual': [1, 0, 0],
 'life': [1, 0, 0],
 'fields': [1, 0, 0],
 'mathematics': [1, 0, 0],
 'astronomy': [1, 0, 0],
 'architecture': [1, 0, 0],
 'literature': [1, 0, 0],
 'music': [1, 0, 0],
 'fine': [1, 0, 0],
 'arts': [1, 0, 0],
 'United': [1, 0, 0],
 'Nations': [1, 0, 0],
 'international': [1, 0, 0],
 'organization': [1, 0, 0],
 'founded': [1, 0, 0],
 '1945': [1, 0, 0],
 'Currently': [1, 0, 0],
 'made': [1, 0, 0],
 '193': [1, 0, 0],
 'Member': [1, 0, 0],
 'States': [1, 0, 0],
 'UN': [1, 0, 0],
 'work': [1, 0, 0],
 'guided': [1, 0, 0],
 'purposes': [1, 0, 0],
 'principles': [1, 0, 0],
 'contained': [1, 0, 0],
 'founding': [1, 0, 0],
 'Charter': [1, 0, 0],
 'evolved': [1, 0, 0],
 'years': [1, 0, 0],
 'keep': [1, 0, 0],
 'pace': [1, 0, 0],
 'rapidly': [1, 0, 0],
 'changing': [1, 0, 0],
 'world': [1, 0, 0],
 'one': [1, 0, 0],
 'thing': [1, 0, 0],
 'stayed': [1, 0, 0],
 'remains': [1, 0, 0],
 'place': [1, 0, 0],
 'Earth': [1, 0, 0],
 'nations': [1, 0, 0],
 'gather': [1, 0, 0],
 'together': [1, 0, 0],
 'discuss': [1, 0, 0],
 'common': [1, 0, 0],
 'problems': [1, 0, 0],
 'find': [1, 0, 0],
 'shared': [1, 0, 0],
 'solutions': [1, 0, 0],
 'benefit': [1, 0, 0],
 'humanity': [1, 0, 0],
 'UN’s': [1, 0, 0],
 'Membership': [1, 0, 0],
 'grown': [1, 0, 0],
 'original': [1, 0, 0],
 '51': [1, 0, 0],
 'current': [1, 0, 0],
 'members': [1, 0, 0],
 'General': [1, 0, 0],
 'Assembly': [1, 0, 0],
 'admitted': [1, 0, 0],
 'membership': [1, 0, 0],
 'decision': [1, 0, 0],
 'upon': [1, 0, 0],
 'recommendation': [1, 0, 0],
 'Security': [1, 0, 0],
 'Council': [1, 0, 0],
 'main': [1, 0, 0],
 'bodies': [1, 0, 0],
 'Economic': [1, 0, 0],
 'Social': [1, 0, 0],
 'Trusteeship': [1, 0, 0],
 'International': [1, 0, 0],
 'Court': [1, 0, 0],
 'Justice': [1, 0, 0],
 'Secretariat': [1, 0, 0],
 'established': [1, 0, 0],
 'Development': [1, 0, 0],
 'Programme': [1, 0, 1],
 'UNDP': [1, 0, 0],
 'worldwide': [1, 0, 0],
 'development': [1, 0, 0],
 'network': [1, 0, 0],
 'significant': [1, 0, 0],
 'multilateral': [1, 0, 0],
 'source': [1, 0, 0],
 'aid': [1, 0, 0],
 'Expanded': [1, 0, 0],
 'Technical': [1, 0, 0],
 'Assistance': [1, 0, 0],
 'Special': [1, 0, 0],
 'Fund': [1, 0, 0],
 'merged': [1, 0, 0],
 '1965': [1, 0, 0],
 'two': [1, 0, 0],
 'institutions': [1, 0, 0],
 'fully': [1, 0, 0],
 'integrated': [1, 0, 0],
 '1971': [1, 0, 0],
 'executive': [1, 0, 0],
 'body': [1, 0, 0],
 'Secretary': [0, 1, 1],
 'Deputy': [0, 1, 1],
 'SecretaryGeneral': [0, 1, 0],
 'Administrator': [0, 1, 0],
 'third': [0, 1, 0],
 'highestranking': [0, 1, 0],
 'member': [0, 1, 0],
 'based': [0, 1, 0],
 'York': [0, 1, 0],
 'City': [0, 1, 0],
 'supported': [0, 1, 0],
 'voluntary': [0, 1, 0],
 'contributions': [0, 1, 0],
 'countries': [0, 1, 0],
 '166': [0, 1, 0],
 'organisation': [0, 1, 0],
 'operates': [0, 1, 0],
 'national': [0, 1, 0],
 'offices': [0, 1, 0],
 'works': [0, 1, 0],
 'local': [0, 1, 1],
 'governments': [0, 1, 0],
 'address': [0, 1, 0],
 'concerns': [0, 1, 0],
 'build': [0, 1, 0],
 'expertise': [0, 1, 0],
 'offers': [0, 1, 0],
 'developing': [0, 1, 0],
 'professional': [0, 1, 0],
 'advice': [0, 1, 0],
 'training': [0, 1, 0],
 'financial': [0, 1, 0],
 'funding': [0, 1, 0],
 'focusing': [0, 1, 0],
 'least': [0, 1, 0],
 'poverty': [0, 1, 0],
 'reduction': [0, 1, 0],
 'HIVAIDS': [0, 1, 0],
 'democratic': [0, 1, 0],
 'governance': [0, 1, 0],
 'energy': [0, 1, 0],
 'environment': [0, 1, 0],
 'crisis': [0, 1, 0],
 'prevention': [0, 1, 0],
 'recovery': [0, 1, 0],
 'achieve': [0, 1, 0],
 'MDGs': [0, 1, 0],
 'support': [0, 1, 0],
 'global': [0, 1, 0],
 'activities': [0, 1, 0],
 'promotes': [0, 1, 0],
 'preservation': [0, 1, 0],
 'human': [0, 1, 0],
 'rights': [0, 1, 0],
 'women’s': [0, 1, 0],
 'empowerment': [0, 1, 0],
 'also': [0, 1, 0],
 'produces': [0, 1, 0],
 'annual': [0, 1, 0],
 'Human': [0, 1, 0],
 'Report': [0, 1, 0],
 'track': [0, 1, 1],
 'assess': [0, 1, 0],
 'progress': [0, 1, 0],
 'addition': [0, 1, 0],
 'releases': [0, 1, 0],
 'regional': [0, 1, 0],
 'Reports': [0, 1, 0],
 'report': [0, 1, 0]}

In [ ]:
import nltk
import numpy as np
nltk.download('punkt')
from nltk.tokenize import word_tokenize

In [ ]:
#query

query=input("Enter the Query")
query=word_tokenize(query)
operators=[]
words=[]
for word in query:
  if word.lower() != 'and' and word.lower() != 'or' and word.lower() != 'not':
    words.append(word)
  else:
    operators.append(word.lower())

if operators[0]=='and':
  bitwise_op =  np.array(der[words[0]]) & np.array(der[words[1]])
elif operators[0]=='or':
  bitwise_op =  np.array(der[words[0]]) | np.array(der[words[1]])
  '''elif word == "not":
    bitwise_op = [not words[0] for words[0] in der[words[1]]]
    bitwise_op = [int(b == True) for b in bitwise_op]'''

operators.pop(0)
words.pop(0)
words.pop(0)

for word in operators:
    if word == "and":
        bitwise_op = bitwise_op & np.array(der[words[0]])
        operators.pop(0)
        words.pop(0)
    elif word == "or":
        bitwise_op = bitwise_op | np.array(der[words[0]])
        operators.pop(0)
        words.pop(0)
    

print(bitwise_op)

Enter the QueryIndia and part or States
[1 0 0]